### ISSUE TITLE
Searchguard properties not exists in elastic context

### ISSUE THREAD

**Issue by kacper-jackiewicz** [fabric8io/openshift-elasticsearch-plugin#180]
I've encountered a problem with configuring the plugin for password different than default for searchguard keystore/truststore on image ose-logging-elasticsearch5:v3.11.98
  
```
    openshift.searchguard:
    keystore:
       path: /etc/elasticsearch/secret/admin.jks
       password: not-default-pass
    truststore:
       path: /etc/elasticsearch/secret/searchguard.truststore
       password: not-default-pass
```
`java.lang.IllegalArgumentException: unknown setting [openshift.searchguard.keystore.password] did you mean any of [openshift.searchguard.keystore.path, openshift.searchguard.truststore.path]?`

Same error for trustore password as well.

According to documentation [action-groups](https://github.com/fabric8io/openshift-elasticsearch-plugin#action-groups) such properties should work.

Is there a problem with my configuration?
